import { t, type DeclarationContent } from "intlayer";
import { Metadata } from "next";

const homePageMetadataContent = {
  key: "home-page-metadata",
  content: {
    title: t({
      en: "Create Next App",
      fr: "Créer une application Next",
      es: "Crear una aplicación Next",
    }),
    description: t({
      en: "Generated by create next app",
      fr: "Généré par create next app",
      es: "Generado por create next app",
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default homePageMetadataContent;
